### ISSUE TITLE
Segfault when module-loopback is loaded

### ISSUE THREAD

**Issue by ghost** [patroclos/PAmix#22]
I have a loopback connected to a null sink, like so:
```bash
pacmd load-module module-null-sink sink_name=screen_recording
pacmd load-module module-loopback source=screen_recording.monitor source_dont_move=true sink=alsa_output.hw_au8830_0 sink_dont_move=true
```

When I do that, GDB says:
```
#0  0x0000003878481f66 in strlen () from /lib64/libc.so.6
No symbol table info available.
#1  0x000000000040bea6 in SourceOutputEntry::update(pa_source_output_info const*) ()
No symbol table info available.
#2  0x0000000000411e84 in PAInterface::cb_source_output_info(pa_context*, pa_source_output_info const*, int, void*) ()
No symbol table info available.
#3  0x00007ffff7d9e4cd in context_get_source_output_info_callback (pd=pd@entry=0x7fffec0015e0, 
    command=command@entry=2, tag=tag@entry=10, t=t@entry=0x7fffec002790, userdata=userdata@entry=0x6bc830)
    at /var/tmp/portage/media-sound/pulseaudio-10.0/work/pulseaudio-10.0/src/pulse/introspect.c:1348
        cb = <optimized out>
        i = {index = 72, name = 0x7fffec00f260 "Loopback to Vortex 2 (Montego II)", owner_module = 17, 
          client = 4294967295, source = 3, sample_spec = {format = PA_SAMPLE_S16LE, rate = 44100, 
            channels = 2 '\002'}, channel_map = {channels = 2 '\002', map = {PA_CHANNEL_POSITION_FRONT_LEFT, 
              PA_CHANNEL_POSITION_FRONT_RIGHT, PA_CHANNEL_POSITION_MONO <repeats 30 times>}}, buffer_usec = 0, 
          source_usec = 0, resample_method = 0x7fffec00f2af "speex-float-1", 
          driver = 0x7fffec00f2be "module-loopback.c", proplist = 0x7fffec010470, corked = 0, volume = {
            channels = 2 '\002', values = {65536, 65536, 0 <repeats 30 times>}}, mute = 0, has_volume = 1, 
          volume_writable = 1, format = 0x7fffec00c000}
        corked = false
        volume_writable = true
        mute = false
        has_volume = true
        o = 0x6bc830
        eol = 1
        __func__ = "context_get_source_output_info_callback"
        __PRETTY_FUNCTION__ = "context_get_source_output_info_callback"
#4  0x00007ffff7b451a2 in run_action (pd=pd@entry=0x7fffec0015e0, r=0x7fffd8000a20, command=2, 
    ts=ts@entry=0x7fffec002790)
    at /var/tmp/portage/media-sound/pulseaudio-10.0/work/pulseaudio-10.0/src/pulsecore/pdispatch.c:288
        callback = 0x7ffff7d9e127 <context_get_source_output_info_callback>
        userdata = 0x6bc830
        tag = 10
        __func__ = "run_action"
        __PRETTY_FUNCTION__ = "run_action"
#5  0x00007ffff7b4554f in pa_pdispatch_run (pd=0x7fffec0015e0, packet=packet@entry=0x7fffd0000950, 
    ancil_data=ancil_data@entry=0x7fffec000c48, userdata=userdata@entry=0x6bdbe0)
    at /var/tmp/portage/media-sound/pulseaudio-10.0/work/pulseaudio-10.0/src/pulsecore/pdispatch.c:341
        r = <optimized out>
        tag = 10
        command = 2
        ts = 0x7fffec002790
        ret = -1
        pdata = <optimized out>
        plen = 4619
        __func__ = "pa_pdispatch_run"
        __PRETTY_FUNCTION__ = "pa_pdispatch_run"
#6  0x00007ffff7d93bd7 in pstream_packet_callback (p=<optimized out>, packet=0x7fffd0000950, 
    ancil_data=0x7fffec000c48, userdata=0x6bdbe0)
    at /var/tmp/portage/media-sound/pulseaudio-10.0/work/pulseaudio-10.0/src/pulse/context.c:349
        c = 0x6bdbe0
        __func__ = "pstream_packet_callback"
        __PRETTY_FUNCTION__ = "pstream_packet_callback"
#7  0x00007ffff7b4819f in do_read (p=p@entry=0x7fffec0009b0, re=re@entry=0x7fffec000b78)
    at /var/tmp/portage/media-sound/pulseaudio-10.0/work/pulseaudio-10.0/src/pulsecore/pstream.c:1012
        d = <optimized out>
        l = <optimized out>
        r = <optimized out>
        release_memblock = 0x0
        __func__ = "do_read"
        __PRETTY_FUNCTION__ = "do_read"
#8  0x00007ffff7b4ac2b in do_pstream_read_write (p=p@entry=0x7fffec0009b0)
    at /var/tmp/portage/media-sound/pulseaudio-10.0/work/pulseaudio-10.0/src/pulsecore/pstream.c:248
        __func__ = "do_pstream_read_write"
        __PRETTY_FUNCTION__ = "do_pstream_read_write"
#9  0x00007ffff7b4b04c in srb_callback (srb=0x7fffec00af80, userdata=0x7fffec0009b0)
    at /var/tmp/portage/media-sound/pulseaudio-10.0/work/pulseaudio-10.0/src/pulsecore/pstream.c:287
        b = <optimized out>
        p = 0x7fffec0009b0
        __func__ = "srb_callback"
        __PRETTY_FUNCTION__ = "srb_callback"
#10 0x00007ffff7b4b923 in srbchannel_rwloop (sr=sr@entry=0x7fffec00af80)
    at /var/tmp/portage/media-sound/pulseaudio-10.0/work/pulseaudio-10.0/src/pulsecore/srbchannel.c:190
No locals.
#11 0x00007ffff7b4b94b in semread_cb (m=<optimized out>, e=<optimized out>, fd=<optimized out>, 
    events=<optimized out>, userdata=0x7fffec00af80)
    at /var/tmp/portage/media-sound/pulseaudio-10.0/work/pulseaudio-10.0/src/pulsecore/srbchannel.c:210
        sr = 0x7fffec00af80
#12 0x00007ffff7da7848 in dispatch_pollfds (m=m@entry=0x6bc3e0)
    at /var/tmp/portage/media-sound/pulseaudio-10.0/work/pulseaudio-10.0/src/pulse/mainloop.c:655
        e = 0x7fffec00b030
        r = 0
        k = 1
        __func__ = "dispatch_pollfds"
        __PRETTY_FUNCTION__ = "dispatch_pollfds"
#13 0x00007ffff7da900a in pa_mainloop_dispatch (m=m@entry=0x6bc3e0)
    at /var/tmp/portage/media-sound/pulseaudio-10.0/work/pulseaudio-10.0/src/pulse/mainloop.c:898
        dispatched = 0
        __func__ = "pa_mainloop_dispatch"
        __PRETTY_FUNCTION__ = "pa_mainloop_dispatch"
#14 0x00007ffff7da9119 in pa_mainloop_iterate (m=m@entry=0x6bc3e0, block=block@entry=1, retval=retval@entry=0x0)
    at /var/tmp/portage/media-sound/pulseaudio-10.0/work/pulseaudio-10.0/src/pulse/mainloop.c:929
        r = 1
        __func__ = "pa_mainloop_iterate"
        __PRETTY_FUNCTION__ = "pa_mainloop_iterate"
#15 0x00007ffff7da915e in pa_mainloop_run (m=0x6bc3e0, retval=retval@entry=0x0)
    at /var/tmp/portage/media-sound/pulseaudio-10.0/work/pulseaudio-10.0/src/pulse/mainloop.c:944
        r = <optimized out>
#16 0x00007ffff7db7bc4 in thread (userdata=0x6bc3a0)
    at /var/tmp/portage/media-sound/pulseaudio-10.0/work/pulseaudio-10.0/src/pulse/thread-mainloop.c:100
        m = 0x6bc3a0
        mask = {__val = {18446744067267100671, 18446744073709551615 <repeats 15 times>}}
        prev_mask = {__val = {0, 206158430211, 0, 2, 4, 64, 0, 206158430210, 0, 0, 472446402651, 0, 0, 
            532575944823, 242533679104, 140737152811040}}
        sa = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {
              0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
#17 0x00007ffff7b5a8e7 in internal_thread_func (userdata=0x6bc590)
    at /var/tmp/portage/media-sound/pulseaudio-10.0/work/pulseaudio-10.0/src/pulsecore/thread-posix.c:81
        t = 0x6bc590
        __func__ = "internal_thread_func"
        __PRETTY_FUNCTION__ = "internal_thread_func"
#18 0x00000038788072e6 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#19 0x00000038784ea59f in clone () from /lib64/libc.so.6
No symbol table info available.
```

**Comment by patroclos** [comment]
Thanks for reporting that. 
I was able to replicate your issue. The audio streams from the module didn't have an application name set in their proplist, so I'm now using the name of the stream as a fallback.
This issue should be resolvend with commit e434ab7f4a1f204f9752dd4a86736ea73b207dea
